server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # 데이터베이스 커넥션 이름
    password: sbs32465169132184! # 데이터베이스 커넥션 비밀번호
    url: jdbc:mysql://localhost:3306/beomlog?useUnicode=true&serverTimezone=Asia/Seoul

  jpa:
    hibernate:
      ddl-auto: create-drop # 옵션은 필요에 따라 변경
    properties:
      hibernate:
        default_batch_size: 100 # 지연로딩 최적화를 위한 옵션
        format_sql: true

  output:
    ansi:
      enabled: always

logging:
  file:
    name: ${user.dir}/log/server_log.log # slf4j를 사용할 때 생기는 로그 파일 경로
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace